Quotes

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -4,21 +4,12 @@ on:
     types: [synchronize, opened, reopened, edited]
 
 jobs:
-  hello_world_job:
-    runs-on: ubuntu-latest
-    name: A job to say hello
-    steps:
-      - uses: actions/checkout@v4
-      # - id: foo
-      #   uses: gencarnacao-cw/test-action@v9
-      #   with:
-      #     context: ${{ toJSON(github) }}
   bash-script:
       runs-on: ubuntu-latest
       if: ${{ github.event_name == 'pull_request' }}
       steps:
         - name: Print the PR title
           run: |
-            echo ${{ github.event.pull_request.title }} | grep -o "GRUB-\d{4,5}" || echo "::error::PR Title does not include JIRA issue number!" && exit 1
+            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d{4,5}" || echo "::error::PR Title does not include JIRA issue number!" && exit 1
 
 
