Tests

diff --git a/.github/workflows/check-pr.yml b/.github/workflows/check-pr.yml
--- a/.github/workflows/check-pr.yml
+++ b/.github/workflows/check-pr.yml
@@ -10,6 +10,15 @@ jobs:
       steps:
         - name: Print the PR title
           run: |
-            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d{4,5}" || echo "::error::PR Title does not include JIRA issue number!" && exit 1
+            # echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d{4,5}" || echo "::error::PR Title does not include JIRA issue number!" && exit 1
+            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d*" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d{4,5}" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep -o "GRUB-\d\{4,5\}" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep "GRUB-" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep "GRUB-\d*" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep "GRUB-\d{4,5}" || echo ""
+            echo "${{ github.event.pull_request.title }}" | grep "GRUB-\d\{4,5\}" || echo ""
+
 
 
